name: Publish package to npm

on:
  push:
    branches:
    - main

# Trusted publishing using OIDC. For more info check:
# https://docs.npmjs.com/trusted-publishers#supported-cicd-providers
permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    if: contains(github.event.head_commit.message, 'ðŸš€ publish(npm):')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: "https://registry.npmjs.org/"

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    # â¬‡ Fix Vitest + Playwright issue
    # - name: Install Playwright browsers
    #   run: pnpm exec playwright install --with-deps

    - name: Run tests (Vitest)
      run: pnpm test

    # Build your package (svelte-kit sync + svelte-package + publint)
    - name: Build package
      run: pnpm prepack

    # Publish `dist/` folder as the npm package
    - name: Publish to npm
      run: pnpm publish --no-git-checks
