name: Publish package to npm

on:
  push:
    branches:
    - main

jobs:
  publish:
    # Trusted publishing using OIDC. For more info check:
    # https://docs.npmjs.com/trusted-publishers#supported-cicd-providers
    permissions:
      id-token: write # Required for OIDC
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)

    if: github.repository == 'AK-Network/permkit' # prevents this action from running on forks
    # if: contains(github.event.head_commit.message, 'ðŸš€ publish(npm):')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
        fetch-depth: 0

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        registry-url: "https://registry.npmjs.org/"
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Create Release Pull Request or Publish to npm
      id: changesets
      uses: changesets/action@v1
      with:
        # This expects you to have a script called release which does a build for your packages and calls changeset publish
        publish: pnpm changeset:release
        version: pnpm changeset:version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_CONFIG_PROVENANCE: true

    # â¬‡ Fix Vitest + Playwright issue
    # - name: Install Playwright browsers
    #   run: pnpm exec playwright install --with-deps

    - name: Run tests (Vitest)
      run: pnpm test

    # Build your package (svelte-kit sync + svelte-package + publint)
    - name: Build package
      run: pnpm prepack

    # Publish `dist/` folder as the npm package
    - name: Publish to npm
      run: pnpm publish --no-git-checks

# name: Publish Package

# on:
#   push:
#     branches:
#     - main
#     tags:
#     - 'v*'

# permissions:
#   id-token: write # Required for OIDC
#   contents: write

# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4

#     - uses: actions/setup-node@v4
#       with:
#         node-version: '20'
#         registry-url: 'https://registry.npmjs.org'

#     - name: Setup pnpm
#       uses: pnpm/action-setup@v4
#       with:
#         version: 10

#     - name: Install dependencies
#       run: pnpm install --frozen-lockfile

#     # Ensure npm 11.5.1 or later is installed
#     - name: Update npm
#       run: npm install -g npm@latest
#     - run: npm i
#     - run: npm test
#     - run: npm run prepack
#     - run: npm publish
